### ISSUE TITLE
Shutdown steps

### ISSUE THREAD

**Issue by wsian** [afilis/h3-shutdown-server#1]
I have installed as given instruction, compile arisc-fw.code, move arisc-fw.code, loader/* to /boot.
What are the next steps to shutdown (orangepi) ?

**Comment by afilis** [comment]
The program is intended for prevention of overheating of orange pi (H2+/H3 based) after switching off.
Overheating usually happens if you are using armbian stretch (mainline) on it.
You should install both the server and the client parts. Then reset your device, use the following command as root:
reboot
The program will be activated.
To shutdown use the following command as root:
poweroff
or
shutdown -h now
After shutdown the board will not heat up.

**Comment by wsian** [comment]
OK, got it. Thanks for sharing.
